
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgwehxjlxhgnmshpnjxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtnd2VoeGpseGhnbm1zaHBuanhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNjY5MjIsImV4cCI6MjA1ODc0MjkyMn0.U2qBmGot0mOuhAmL01cUKvJlt74rfRidv_T0q8zC6CU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Type-safe helper for reporter_jobs table operations
export const reporterJobsTable = () => supabase.from('reporter_jobs');
